services:
  eshopdb:
     container_name: eshopdb
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: eshopdb
     restart: always
     ports:
        - "5432:5432"
     volumes:
        - postgres_eshopdb:/var/lib/postgresql
  seq:
     container_name: seq
     environment:
       - ACCEPT_EULA=Y
       - SEQ_FIRSTRUN_ADMINUSERNAME=Admin
       - SEQ_FIRSTRUN_ADMINPASSWORD=P@ssw0rd
     restart: always
     ports:
        - "5341:5341"
        - "9091:80"
  distributedCache:
      container_name: distributedCache
      restart: always
      ports:
        - "6379:6379"